name: Build & Deploy
on:
  push:
    branches:
      - main
jobs:
  clone:
    name: Clone
    runs-on: self-hosted
    steps:
    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2
      with:
        if_key_exists: replace
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.QDP_KEY }}
        port: ${{ secrets.PORT }}
        script: whoami