name: Build & Deploy
on:
  push:
    branches:
      - main
jobs:
  clone:
    name: Pull
    runs-on: self-hosted
    steps:
      - run: cd /var/www/qdp ; git stash ; git pull https://github.com/fernandosoder/qdp.git ; npm run sass-build