name: Build & Deploy
on:
  push:
    branches:
      - main
jobs:
  clone:
    name: Pull
    runs-on: self-hosted
    steps:
    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.QDP_KEY }}
        known_hosts: unnecessary
        if_key_exists: ignore
        script: |
          cd /var/www/qdp
          git pull
