name: Build & Deploy
on:
  push:
    branches:
      - main
jobs:
  obs:
    example-job:
      name: Save output
      steps:
      - uses: actions/checkout@v2
      - name: Run script file
        run: |
          ls
        shell: bash